name: build

on:
  pull_request:
    branches: [main]

jobs:
  pull_request_unit_test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js 12
        uses: actions/setup-node@v1
        with:
          node-version: 12

      - name: Bootstrapping packages
        run: yarn ci

      - name: Test UI components and gernerate coverage report
        run: yarn test -- --coverage

      - name: Upload coverage to Codecov
        uses: codecov/codecov-action@v1

      - name: Test Storybook UI
        run: yarn run build-storybook
