name: UI Components Unit Tests

on:
  pull_request:
    branches: [main]

jobs:
  pull_request_unit_test:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Use Node.js 12
        uses: actions/setup-node@v1
        with:
          node-version: 12

      - name: Bootstrapping packages
        run: npm ci

      - name: Test UI Components
        run: npm test

      - name: Test Storybook UI
        run: npm run build-storybook
